version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    ports:
      - ${PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /data:/var/lib/postgresql/data
    restart: unless-stopped
